compatibility_date = "2022-09-16"
name = "visit-counter"
send_metrics = true
usage_model = 'bundled'
workers_dev = true

[[kv_namespaces]]
binding = "VISIT_COUNTER"
id = "011d2300c1b24c028a7b99d36306b65b"
preview_id = "e97079cd956c4eada517df1e9b3f48a2"
