compatibility_date = "2021-10-15"
compatibility_flags = []
kv_namespaces = [{binding = "VISIT_COUNTER", preview_id = "e97079cd956c4eada517df1e9b3f48a2", id = "011d2300c1b24c028a7b99d36306b65b"}]
name = "visit-counter"
route = ''
type = "javascript"
usage_model = ''
workers_dev = true
zone_id = ''
